"use client";
import {useParams} from "next/navigation";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {api,BASE} from "@/lib/api"; import {auth} from "@/lib/auth";
import type {Book} from "@/types/api"; import {BookCard} from "@/components/BookCard"; import {useState} from "react";
type Rag={answer:string;sources:{label:string;source:string;chunkIndex:string;snippet:string}[]};
export default function BookPage(){
 const {id}=useParams<{id:string}>();const qc=useQueryClient(); const q=useQuery({queryKey:["book",id],queryFn:()=>api<Book>(`/api/books/${id}`)}); const similar=useQuery({queryKey:["similar",id],queryFn:()=>api<Book[]>(`/api/books/${id}/similar?limit=4`),enabled:!!q.data});
 const [summary,setSummary]=useState("");const [page,setPage]=useState("");const [percentage,setPercentage]=useState("");const [question,setQuestion]=useState("");const [rag,setRag]=useState<Rag>();
 const add=useMutation({mutationFn:()=>api(`/api/library/books/${id}`,{method:"POST",body:JSON.stringify({status:"WANT_TO_READ"})})});
 const summarize=useMutation({mutationFn:()=>api<{answer:string}>(`/api/books/${id}/summary?type=SHORT`,{method:"POST"}),onSuccess:r=>setSummary(r.answer)});
 const progress=useMutation({mutationFn:()=>api(`/api/reading/${id}`,{method:"PUT",body:JSON.stringify({currentPage:page?Number(page):undefined,percentage:percentage?Number(percentage):undefined})})});
 const chat=useMutation({mutationFn:()=>api<Rag>(`/api/books/${id}/chat`,{method:"POST",body:JSON.stringify({question})}),onSuccess:setRag});
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const form=new FormData();form.append("file",f);let r=await fetch(`${BASE}/api/documents?bookId=${id}`,{method:"POST",headers:{Authorization:`Bearer ${auth.access()}`},body:form});if(r.status===401)throw new Error("Sign in again before uploading");if(!r.ok)throw new Error("Upload failed");qc.invalidateQueries({queryKey:["documents"]})}
 const b=q.data;if(!b)return <main className="shell"><p>Loading…</p></main>;
 return <main className="shell"><div className="bookdetail"><div className="cover">{b.coverUrl?<img src={b.coverUrl} alt=""/>:<span>{b.title[0]}</span>}</div><div><p className="eyebrow">{b.categories?.join(" · ")||"Book"}</p><h1 style={{fontSize:50,letterSpacing:"-.05em",margin:"8px 0"}}>{b.title}</h1><p className="lede">{b.authors.join(", ")} · {b.publishedYear??"Unknown year"} · {b.pageCount??"?"} pages</p><p className="muted" style={{lineHeight:1.65}}>{b.description??"No catalog description available."}</p><div className="actions"><button className="btn" onClick={()=>add.mutate()}>+ Want to read</button><button className="btn secondary" onClick={()=>summarize.mutate()}>{summarize.isPending?"Generating…":"AI summary"}</button></div>{summary&&<div className="panel" style={{marginTop:22}}><p className="eyebrow">Catalog-grounded summary</p><p style={{whiteSpace:"pre-wrap",lineHeight:1.6}}>{summary}</p></div>}</div></div>
 <div className="panel" style={{marginTop:28}}><p className="eyebrow">Reading progress</p><div className="row"><input className="input" style={{maxWidth:180}} type="number" min="0" placeholder="Current page" value={page} onChange={e=>setPage(e.target.value)}/><input className="input" style={{maxWidth:180}} type="number" min="0" max="100" placeholder="Percent" value={percentage} onChange={e=>setPercentage(e.target.value)}/><button className="btn secondary" onClick={()=>progress.mutate()}>{progress.isPending?"Saving…":"Save progress"}</button></div></div>
 <div className="panel" style={{marginTop:28}}><p className="eyebrow">Chat with this book</p><p className="muted">Upload only content you are allowed to use. The RAG query is filtered by your user ID and this book ID.</p><input type="file" accept=".pdf,.epub,.txt,.md,.markdown" onChange={upload}/><div className="searchbox"><input className="input" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does the source say about...?"/><button className="btn" onClick={()=>chat.mutate()}>{chat.isPending?"Retrieving…":"Ask"}</button></div>{rag&&<><p style={{whiteSpace:"pre-wrap",lineHeight:1.6}}>{rag.answer}</p>{rag.sources.map(s=><div key={s.label} className="panel" style={{padding:12,marginTop:8}}><b>[{s.label}] {s.source}</b><p className="muted">{s.snippet}</p></div>)}</>}</div>
 {similar.data?.length?<section style={{marginTop:38}}><div className="sectionhead"><h2>Similar books</h2></div><div className="grid">{similar.data.map(x=><BookCard key={x.id} book={x}/>)}</div></section>:null}
 </main>
}
